// Auto-generated by decompiler.py from adder_demo -- do not hand-edit.

module sky130_fd_sc_hd__dfrtp_2 (
    input CLK,
    input D,
    input RESET_B,
    output reg Q
);
    // tier1(known-cell)
    always @(posedge CLK or negedge RESET_B) begin
        if (!RESET_B) begin
            Q <= 1'b0;
        end
        else begin
            Q <= D;
        end
    end
endmodule

module cluster_type_0 (
    input B,
    input clk,
    input en,
    input rst_n,
    output [7:0] A_10_bus
);
    wire D_10;
    wire D_11;
    wire D_12;
    wire D_13;
    wire D_14;
    wire D_15;
    wire D_16;
    wire D_17;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign D_13 = (A_10_bus[4] & ~en) | (A_10_bus[0] & en);
    assign D_14 = (A_10_bus[5] & ~en) | (A_10_bus[1] & en);
    assign D_15 = (A_10_bus[6] & ~en) | (A_10_bus[4] & en);
    assign D_10 = (A_10_bus[1] & ~en) | (A_10_bus[2] & en);
    assign D_11 = (A_10_bus[2] & ~en) | (A_10_bus[3] & en);
    assign D_17 = (A_10_bus[0] & ~en) | (A_10_bus[7] & en);
    assign D_12 = (A_10_bus[3] & ~en) | (B & en);
    assign D_16 = (A_10_bus[7] & ~en) | (A_10_bus[5] & en);
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i3 (.CLK(clk), .D(D_13), .RESET_B(rst_n), .Q(A_10_bus[4]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i4 (.CLK(clk), .D(D_14), .RESET_B(rst_n), .Q(A_10_bus[5]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i5 (.CLK(clk), .D(D_15), .RESET_B(rst_n), .Q(A_10_bus[6]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i6 (.CLK(clk), .D(D_10), .RESET_B(rst_n), .Q(A_10_bus[1]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i10 (.CLK(clk), .D(D_11), .RESET_B(rst_n), .Q(A_10_bus[2]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i11 (.CLK(clk), .D(D_17), .RESET_B(rst_n), .Q(A_10_bus[0]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i12 (.CLK(clk), .D(D_12), .RESET_B(rst_n), .Q(A_10_bus[3]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i13 (.CLK(clk), .D(D_16), .RESET_B(rst_n), .Q(A_10_bus[7]));
endmodule

module cluster_type_1 (
    input [7:0] A_10_bus,
    input [7:0] A0_4_bus,
    output [8:0] A_2_bus
);
    wire A1;
    wire A1_1;
    wire A2;
    wire A2_1;
    wire A2_2;
    wire A2_3;
    wire A3;
    wire A3_1;
    wire A3_2;
    wire A_11;
    wire A_12;
    wire A_13;
    wire A_14;
    wire A_15;
    wire A_16;
    wire A_18;
    wire A_19;
    wire A_20;
    wire A_21;
    wire A_22;
    wire A_23;
    wire B1;
    wire B1_1;
    wire B1_2;
    wire B_2;
    wire B_3;
    wire B_5;
    wire B_6;
    wire B_7;
    wire B_8;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign A_2_bus[2] = (~A_10_bus[2] & A_10_bus[3] & A0_4_bus[3] & ~A0_4_bus[2]) | (A_10_bus[2] & A_10_bus[3] & A0_4_bus[3] & A0_4_bus[2]) | (~A_10_bus[2] & ~A_10_bus[3] & A0_4_bus[2]) | (~A_10_bus[2] & ~A0_4_bus[3] & A0_4_bus[2]) | (A_10_bus[2] & ~A_10_bus[3] & ~A0_4_bus[2]) | (A_10_bus[2] & ~A0_4_bus[3] & ~A0_4_bus[2]);
    assign A_2_bus[5] = (~A_10_bus[3] & A0_4_bus[3]) | (A_10_bus[3] & ~A0_4_bus[3]);
    assign B1 = (A_10_bus[1] & A0_4_bus[1] & A3) | B_2;
    assign A1 = ~A_10_bus[6] & ~A0_4_bus[6];
    assign A_11 = ~A_10_bus[5] & ~A0_4_bus[5];
    assign A_12 = ~A_10_bus[0] & ~A0_4_bus[0];
    assign A_14 = ~A_13 & ~B_3;
    assign A2_1 = (~A1_1 & A_15) | (~A2 & A_15);
    assign A_2_bus[7] = (~A1 & ~A2_1) | A_16;
    assign A_16 = A_10_bus[6] & A0_4_bus[6];
    assign A3_1 = (~A_10_bus[2] & A0_4_bus[2]) | (A_10_bus[2] & ~A0_4_bus[2]);
    assign A_2_bus[8] = (~A_18 & B_5) | (A_18 & ~B_5);
    assign A_2_bus[6] = (~A_14 & A2_2) | (A_14 & ~A2_2);
    assign A_2_bus[4] = (~A_19 & A2_3) | (A_19 & ~A2_3);
    assign A2 = (A_14 & A2_2 & A_18) | B1_1;
    assign A1_1 = A0_4_bus[4] | A_10_bus[4];
    assign B_6 = A_10_bus[0] & A0_4_bus[0];
    assign A_20 = A0_4_bus[1] | A_10_bus[1];
    assign B_8 = (A_19 & A2_3) | ~B_7;
    assign B_2 = A_10_bus[5] & A0_4_bus[5];
    assign A_18 = ~A_12 & ~B_6;
    assign A_21 = ~A_11 & ~B_2;
    assign B_5 = (A_14 & A2_2) | A_13;
    assign A3_2 = A0_4_bus[0] | A_10_bus[0];
    assign B_3 = ~A_10_bus[7] & ~A0_4_bus[7];
    assign A_22 = ~A_15 | ~A1_1;
    assign B1_2 = A_10_bus[2] & A0_4_bus[2];
    assign B1_1 = (A_10_bus[7] & A0_4_bus[7] & A3_2) | B_6;
    assign A3 = A0_4_bus[5] | A_10_bus[5];
    assign A_2_bus[0] = (~A_22 & ~A2) | (A_22 & A2);
    assign A2_2 = (A_19 & A2_3 & A_21) | B1;
    assign A_2_bus[1] = (~A_21 & B_8) | (A_21 & ~B_8);
    assign A_2_bus[3] = (~A_23 & ~A2_1) | (A_23 & A2_1);
    assign A_15 = ~A_10_bus[4] | ~A0_4_bus[4];
    assign B_7 = ~A_10_bus[1] | ~A0_4_bus[1];
    assign A_23 = ~A_16 & ~A1;
    assign A2_3 = A_20 & B_7;
    assign A_19 = (A_10_bus[3] & A0_4_bus[3] & A3_1) | B1_2;
    assign A_13 = A_10_bus[7] & A0_4_bus[7];
endmodule

module cluster_type_2 (
    input [8:0] A_2_bus,
    output S
);
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign S = A_2_bus[0] & ~A_2_bus[1] & ~A_2_bus[2] & A_2_bus[3] & ~A_2_bus[4] & ~A_2_bus[5] & A_2_bus[6] & A_2_bus[7] & A_2_bus[8];
endmodule

module adder_demo (
    input A,
    input B,
    input clk,
    input en,
    input rst_n,
    output S
);
    wire [7:0] A_10_bus;
    wire [7:0] A0_bus;
    wire [8:0] A_2_bus;
    cluster_type_1 cluster_type_1_i0 (.A_10_bus(A_10_bus), .A0_4_bus(A0_bus), .A_2_bus(A_2_bus));
    cluster_type_0 cluster_type_0_i1 (.B(B), .clk(clk), .en(en), .rst_n(rst_n), .A_10_bus(A_10_bus));
    cluster_type_0 cluster_type_0_i2 (.B(A), .clk(clk), .en(en), .rst_n(rst_n), .A_10_bus(A0_bus));
    cluster_type_2 cluster_type_2_i3 (.A_2_bus(A_2_bus), .S(S));
endmodule
