// Auto-generated by decompiler.py from adder_demo -- do not hand-edit.

module sky130_fd_sc_hd__a21bo_2 (
    input A1,
    input A2,
    input B1_N,
    output X
);
    // combinational(z3-truth-table)
    assign X = (A1 & A2) | ~B1_N;
endmodule

module sky130_fd_sc_hd__a21boi_2 (
    input A1,
    input A2,
    input B1_N,
    output Y
);
    // combinational(z3-truth-table)
    assign Y = (~A1 & B1_N) | (~A2 & B1_N);
endmodule

module sky130_fd_sc_hd__a21o_2 (
    input A1,
    input A2,
    input B1,
    output X
);
    // combinational(z3-truth-table)
    assign X = (A1 & A2) | B1;
endmodule

module sky130_fd_sc_hd__a31o_2 (
    input A1,
    input A2,
    input A3,
    input B1,
    output X
);
    // combinational(z3-truth-table)
    assign X = (A1 & A2 & A3) | B1;
endmodule

module sky130_fd_sc_hd__and2_2 (
    input A,
    input B,
    output X
);
    // combinational(z3-truth-table)
    assign X = A & B;
endmodule

module sky130_fd_sc_hd__and3_2 (
    input A,
    input B,
    input C,
    output X
);
    // combinational(z3-truth-table)
    assign X = A & B & C;
endmodule

module sky130_fd_sc_hd__and4bb_2 (
    input A_N,
    input B_N,
    input C,
    input D,
    output X
);
    // combinational(z3-truth-table)
    assign X = ~A_N & ~B_N & C & D;
endmodule

module sky130_fd_sc_hd__dfrtp_2 (
    input CLK,
    input D,
    input RESET_B,
    output reg Q
);
    // tier1(known-cell)
    always @(posedge CLK or negedge RESET_B) begin
        if (!RESET_B) begin
            Q <= 1'b0;
        end
        else begin
            Q <= D;
        end
    end
endmodule

module sky130_fd_sc_hd__mux2_1 (
    input A0,
    input A1,
    input S,
    output X
);
    // combinational(z3-truth-table)
    assign X = (A0 & ~S) | (A1 & S);
endmodule

module sky130_fd_sc_hd__nand2_2 (
    input A,
    input B,
    output Y
);
    // combinational(z3-truth-table)
    assign Y = ~A | ~B;
endmodule

module sky130_fd_sc_hd__nor2_2 (
    input A,
    input B,
    output Y
);
    // combinational(z3-truth-table)
    assign Y = ~A & ~B;
endmodule

module sky130_fd_sc_hd__o21bai_2 (
    input A1,
    input A2,
    input B1_N,
    output Y
);
    // combinational(z3-truth-table)
    assign Y = (~A1 & ~A2) | B1_N;
endmodule

module sky130_fd_sc_hd__or2_2 (
    input A,
    input B,
    output X
);
    // combinational(z3-truth-table)
    assign X = B | A;
endmodule

module sky130_fd_sc_hd__xnor2_2 (
    input A,
    input B,
    output Y
);
    // combinational(z3-truth-table)
    assign Y = (~A & ~B) | (A & B);
endmodule

module sky130_fd_sc_hd__xor2_2 (
    input A,
    input B,
    output X
);
    // combinational(z3-truth-table)
    assign X = (~A & B) | (A & ~B);
endmodule

module cluster_type_0 (
    input clk,
    input B,
    input rst_n,
    input en,
    output [7:0] A_10_bus
);
    wire D_10;
    wire D_11;
    wire D_12;
    wire D_13;
    wire D_14;
    wire D_15;
    wire D_16;
    wire D_17;
    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_i0 (.A0(A_10_bus[2]), .A1(A_10_bus[3]), .S(en), .X(D_10));
    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_i1 (.A0(A_10_bus[3]), .A1(A_10_bus[4]), .S(en), .X(D_11));
    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_i2 (.A0(A_10_bus[4]), .A1(B), .S(en), .X(D_12));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i3 (.CLK(clk), .D(D_13), .RESET_B(rst_n), .Q(A_10_bus[5]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i4 (.CLK(clk), .D(D_14), .RESET_B(rst_n), .Q(A_10_bus[6]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i5 (.CLK(clk), .D(D_15), .RESET_B(rst_n), .Q(A_10_bus[7]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i6 (.CLK(clk), .D(D_10), .RESET_B(rst_n), .Q(A_10_bus[2]));
    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_i7 (.A0(A_10_bus[7]), .A1(A_10_bus[5]), .S(en), .X(D_15));
    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_i8 (.A0(A_10_bus[0]), .A1(A_10_bus[6]), .S(en), .X(D_16));
    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_i9 (.A0(A_10_bus[5]), .A1(A_10_bus[1]), .S(en), .X(D_13));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i10 (.CLK(clk), .D(D_11), .RESET_B(rst_n), .Q(A_10_bus[3]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i11 (.CLK(clk), .D(D_17), .RESET_B(rst_n), .Q(A_10_bus[1]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i12 (.CLK(clk), .D(D_12), .RESET_B(rst_n), .Q(A_10_bus[4]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i13 (.CLK(clk), .D(D_16), .RESET_B(rst_n), .Q(A_10_bus[0]));
    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_i14 (.A0(A_10_bus[1]), .A1(A_10_bus[0]), .S(en), .X(D_17));
    sky130_fd_sc_hd__mux2_1 sky130_fd_sc_hd__mux2_1_i15 (.A0(A_10_bus[6]), .A1(A_10_bus[2]), .S(en), .X(D_14));
endmodule

module cluster_type_1 (
    input [7:0] A_10_bus,
    input [7:0] A0_2_bus,
    output [8:0] A_2_bus
);
    wire A1_1;
    wire A1_2;
    wire A2;
    wire A2_1;
    wire A2_2;
    wire A2_3;
    wire A3;
    wire A3_1;
    wire A3_2;
    wire A_12;
    wire A_13;
    wire A_14;
    wire A_15;
    wire A_16;
    wire A_17;
    wire A_18;
    wire A_19;
    wire A_20;
    wire A_21;
    wire A_22;
    wire A_23;
    wire A_24;
    wire B1;
    wire B1_1;
    wire B1_2;
    wire B_1_1;
    wire B_2;
    wire B_3;
    wire B_4;
    wire B_5;
    wire B_6;
    wire B_7;
    sky130_fd_sc_hd__a31o_2 sky130_fd_sc_hd__a31o_2_i0 (.A1(A_10_bus[2]), .A2(A0_2_bus[2]), .A3(A3), .B1(B_1_1), .X(B1));
    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_i1 (.A(A_10_bus[7]), .B(A0_2_bus[7]), .Y(A1_1));
    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_i2 (.A(A_10_bus[6]), .B(A0_2_bus[6]), .Y(A_12));
    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_i3 (.A(A_10_bus[1]), .B(A0_2_bus[1]), .Y(A_13));
    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_i4 (.A(A_14), .B(B_2), .Y(A_15));
    sky130_fd_sc_hd__a21boi_2 sky130_fd_sc_hd__a21boi_2_i5 (.A1(A1_2), .A2(A2), .B1_N(A_16), .Y(A2_1));
    sky130_fd_sc_hd__o21bai_2 sky130_fd_sc_hd__o21bai_2_i6 (.A1(A1_1), .A2(A2_1), .B1_N(A_17), .Y(A_2_bus[7]));
    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_i7 (.A(A_18), .B(B_3), .X(A_2_bus[5]));
    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_i8 (.A(A_10_bus[7]), .B(A0_2_bus[7]), .X(A_17));
    sky130_fd_sc_hd__xor2_2 sky130_fd_sc_hd__xor2_2_i9 (.A(A_10_bus[3]), .B(A0_2_bus[3]), .X(A3_1));
    sky130_fd_sc_hd__xor2_2 sky130_fd_sc_hd__xor2_2_i10 (.A(A_19), .B(B_4), .X(A_2_bus[8]));
    sky130_fd_sc_hd__xor2_2 sky130_fd_sc_hd__xor2_2_i11 (.A(A_15), .B(A2_2), .X(A_2_bus[6]));
    sky130_fd_sc_hd__xor2_2 sky130_fd_sc_hd__xor2_2_i12 (.A(A_20), .B(A2_3), .X(A_2_bus[4]));
    sky130_fd_sc_hd__a31o_2 sky130_fd_sc_hd__a31o_2_i13 (.A1(A_15), .A2(A2_2), .A3(A_19), .B1(B1_1), .X(A2));
    sky130_fd_sc_hd__or2_2 sky130_fd_sc_hd__or2_2_i14 (.A(A_10_bus[5]), .B(A0_2_bus[5]), .X(A1_2));
    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_i15 (.A(A_10_bus[1]), .B(A0_2_bus[1]), .X(B_5));
    sky130_fd_sc_hd__or2_2 sky130_fd_sc_hd__or2_2_i16 (.A(A_10_bus[2]), .B(A0_2_bus[2]), .X(A_21));
    sky130_fd_sc_hd__a21bo_2 sky130_fd_sc_hd__a21bo_2_i17 (.A1(A_20), .A2(A2_3), .B1_N(B_6), .X(B_7));
    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_i18 (.A(A_10_bus[6]), .B(A0_2_bus[6]), .X(B_1_1));
    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_i19 (.A(A_13), .B(B_5), .Y(A_19));
    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_i20 (.A(A_12), .B(B_1_1), .Y(A_22));
    sky130_fd_sc_hd__a21o_2 sky130_fd_sc_hd__a21o_2_i21 (.A1(A_15), .A2(A2_2), .B1(A_14), .X(B_4));
    sky130_fd_sc_hd__or2_2 sky130_fd_sc_hd__or2_2_i22 (.A(A_10_bus[1]), .B(A0_2_bus[1]), .X(A3_2));
    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_i23 (.A(A_10_bus[0]), .B(A0_2_bus[0]), .Y(B_2));
    sky130_fd_sc_hd__nand2_2 sky130_fd_sc_hd__nand2_2_i24 (.A(A_16), .B(A1_2), .Y(A_23));
    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_i25 (.A(A_10_bus[3]), .B(A0_2_bus[3]), .X(B1_2));
    sky130_fd_sc_hd__a31o_2 sky130_fd_sc_hd__a31o_2_i26 (.A1(A_10_bus[0]), .A2(A0_2_bus[0]), .A3(A3_2), .B1(B_5), .X(B1_1));
    sky130_fd_sc_hd__or2_2 sky130_fd_sc_hd__or2_2_i27 (.A(A_10_bus[6]), .B(A0_2_bus[6]), .X(A3));
    sky130_fd_sc_hd__xnor2_2 sky130_fd_sc_hd__xnor2_2_i28 (.A(A_23), .B(A2), .Y(A_2_bus[0]));
    sky130_fd_sc_hd__a31o_2 sky130_fd_sc_hd__a31o_2_i29 (.A1(A_20), .A2(A2_3), .A3(A_22), .B1(B1), .X(A2_2));
    sky130_fd_sc_hd__xor2_2 sky130_fd_sc_hd__xor2_2_i30 (.A(A_22), .B(B_7), .X(A_2_bus[1]));
    sky130_fd_sc_hd__xnor2_2 sky130_fd_sc_hd__xnor2_2_i31 (.A(A_24), .B(A2_1), .Y(A_2_bus[3]));
    sky130_fd_sc_hd__nand2_2 sky130_fd_sc_hd__nand2_2_i32 (.A(A_10_bus[5]), .B(A0_2_bus[5]), .Y(A_16));
    sky130_fd_sc_hd__nand2_2 sky130_fd_sc_hd__nand2_2_i33 (.A(A_10_bus[2]), .B(A0_2_bus[2]), .Y(B_6));
    sky130_fd_sc_hd__nor2_2 sky130_fd_sc_hd__nor2_2_i34 (.A(A_17), .B(A1_1), .Y(A_24));
    sky130_fd_sc_hd__nand2_2 sky130_fd_sc_hd__nand2_2_i35 (.A(A_10_bus[4]), .B(A0_2_bus[4]), .Y(A_18));
    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_i36 (.A(A_21), .B(B_6), .X(A2_3));
    sky130_fd_sc_hd__a31o_2 sky130_fd_sc_hd__a31o_2_i37 (.A1(A_10_bus[4]), .A2(A0_2_bus[4]), .A3(A3_1), .B1(B1_2), .X(A_20));
    sky130_fd_sc_hd__xnor2_2 sky130_fd_sc_hd__xnor2_2_i38 (.A(A_18), .B(A3_1), .Y(A_2_bus[2]));
    sky130_fd_sc_hd__or2_2 sky130_fd_sc_hd__or2_2_i39 (.A(A_10_bus[4]), .B(A0_2_bus[4]), .X(B_3));
    sky130_fd_sc_hd__and2_2 sky130_fd_sc_hd__and2_2_i40 (.A(A_10_bus[0]), .B(A0_2_bus[0]), .X(A_14));
endmodule

module cluster_type_2 (
    input [8:0] A_2_bus,
    output S
);
    wire C_2;
    wire D_1;
    sky130_fd_sc_hd__and4bb_2 sky130_fd_sc_hd__and4bb_2_i0 (.A_N(A_2_bus[1]), .B_N(A_2_bus[4]), .C(A_2_bus[6]), .D(A_2_bus[8]), .X(D_1));
    sky130_fd_sc_hd__and3_2 sky130_fd_sc_hd__and3_2_i1 (.A(A_2_bus[0]), .B(A_2_bus[3]), .C(A_2_bus[7]), .X(C_2));
    sky130_fd_sc_hd__and4bb_2 sky130_fd_sc_hd__and4bb_2_i2 (.A_N(A_2_bus[2]), .B_N(A_2_bus[5]), .C(C_2), .D(D_1), .X(S));
endmodule

module adder_demo (
    input clk,
    input A,
    input B,
    input rst_n,
    input en,
    output S
);
    wire [7:0] A_10_bus;
    wire [7:0] A0_bus;
    wire [8:0] A_2_bus;
    cluster_type_1 cluster_type_1_i0 (.A_10_bus(A_10_bus), .A0_2_bus(A0_bus), .A_2_bus(A_2_bus));
    cluster_type_0 cluster_type_0_i1 (.clk(clk), .B(B), .rst_n(rst_n), .en(en), .A_10_bus(A_10_bus));
    cluster_type_0 cluster_type_0_i2 (.clk(clk), .B(A), .rst_n(rst_n), .en(en), .A_10_bus(A0_bus));
    cluster_type_2 cluster_type_2_i3 (.A_2_bus(A_2_bus), .S(S));
endmodule
