// Auto-generated by decompiler.py from puzzle -- do not hand-edit.

module sky130_fd_sc_hd__dfrtp_2 (
    input CLK,
    input D,
    input RESET_B,
    output reg Q
);
    // tier1(known-cell)
    always @(posedge CLK or negedge RESET_B) begin
        if (!RESET_B) begin
            Q <= 1'b0;
        end
        else begin
            Q <= D;
        end
    end
endmodule

module sky130_fd_sc_hd__dfstp_2 (
    input CLK,
    input D,
    input SET_B,
    output reg Q
);
    // tier2(characterized)
    always @(posedge CLK or negedge SET_B) begin
        if (!SET_B) begin
            Q <= 1'b1;
        end
        else begin
            Q <= D;
        end
    end
endmodule

module sky130_fd_sc_hd__dfxtp_2 (
    input CLK,
    input D,
    output reg Q
);
    // tier2(characterized)
    always @(posedge CLK) begin
        begin
            Q <= D;
        end
    end
endmodule

module cluster_type_0 (
    input A_40,
    input A_41,
    input A_42,
    input A_43,
    input A_8,
    input I,
    input clk,
    input rst_n,
    output [10:0] A_48_bus
);
    wire A1_23;
    wire A1_24;
    wire A1_25;
    wire A1_26;
    wire A1_27;
    wire A1_28;
    wire A1_31;
    wire A2_1;
    wire A2_20;
    wire A2_21;
    wire A2_22;
    wire A2_23;
    wire A2_24;
    wire A2_25;
    wire A2_26;
    wire A2_27;
    wire A2_28;
    wire A2_31;
    wire A3_11;
    wire A3_12;
    wire A3_13;
    wire A3_14;
    wire A3_15;
    wire A3_16;
    wire A3_17;
    wire A_10;
    wire A_11;
    wire A_12;
    wire A_37;
    wire A_39;
    wire A_44;
    wire A_45;
    wire A_47;
    wire A_49;
    wire A_50;
    wire A_52;
    wire A_53;
    wire A_N_1;
    wire A_N_2;
    wire A_N_3;
    wire A_N_4;
    wire A_N_5;
    wire A_N_6;
    wire A_N_7;
    wire B1_16;
    wire B1_17;
    wire B1_18;
    wire B1_19;
    wire B1_2;
    wire B1_20;
    wire B1_21;
    wire B1_22;
    wire B1_23;
    wire B1_24;
    wire B1_25;
    wire B_19;
    wire B_2;
    wire B_20;
    wire B_21;
    wire B_22;
    wire B_23;
    wire B_24;
    wire B_3;
    wire D_1;
    wire D_11;
    wire D_12;
    wire D_13;
    wire D_14;
    wire D_15;
    wire D_16;
    wire D_17;
    wire D_18;
    wire D_19;
    wire D_2;
    wire D_20;
    wire D_21;
    wire D_22;
    wire D_23;
    wire D_24;
    wire D_26;
    wire D_27;
    wire D_29;
    wire D_30;
    wire D_31;
    wire D_34;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign A_48_bus[0] = A1_24 & ~A_N_4;
    assign A_48_bus[1] = A1_27 & ~A_N_1;
    assign A_48_bus[2] = A_10 & ~A_12;
    assign A_48_bus[3] = ~A_47 & A_49;
    assign A_48_bus[4] = A_37 & ~A_52;
    assign A_48_bus[5] = A1_31 & ~A_N_7;
    assign A_48_bus[6] = A1_25 & ~A_N_3;
    assign A_48_bus[7] = A1_26 & ~A_N_5;
    assign A_48_bus[8] = A1_28 & ~A_N_6;
    assign A_48_bus[9] = A1_23 & ~A_N_2;
    assign A_48_bus[10] = A_44 & ~A_53;
    assign D_12 = (~A_40 & ~A_41 & A_42 & ~A_43 & A_52 & A_8 & I) | A_37;
    assign D_15 = (~A_40 & ~A_41 & ~A_42 & A_43 & A_53 & A_8 & I) | A_44;
    assign D_22 = (A_40 & A_41 & ~A_42 & ~A_43 & A_8 & A_N_4 & I) | A1_24;
    assign D_21 = (~A_40 & A_41 & ~A_42 & ~A_43 & A_47 & A_8 & I) | A_49;
    assign D_23 = (~A_40 & A_41 & ~A_42 & A_43 & A_8 & A_N_5 & I) | A1_26;
    assign D_24 = (A_40 & ~A_41 & A_42 & A_43 & A_8 & A_N_3 & I) | A1_25;
    assign D_30 = (A_40 & ~A_41 & A_42 & ~A_43 & A_8 & A_N_1 & I) | A1_27;
    assign D_14 = (~A_40 & ~A_41 & A_42 & A_43 & A_8 & A_N_2 & I) | A1_23;
    assign D_27 = (A_40 & ~A_41 & ~A_42 & A_43 & A_8 & A_N_6 & I) | A1_28;
    assign D_1 = (A_12 & A_40 & ~A_41 & ~A_42 & ~A_43 & A_8 & I) | A_10;
    assign D_34 = (~A_40 & ~A_41 & ~A_42 & ~A_43 & A_8 & A_N_7 & I) | A1_31;
    assign B1_2 = B_3 | A_11 | B_2 | A_10;
    assign D_2 = (A2_1 & B1_2) | (A_12 & B1_2);
    assign B_19 = ~I | ~A_8;
    assign B1_16 = (I & A_8 & A3_11) | A_N_1;
    assign B1_17 = (I & A_8 & A3_12) | A_N_2;
    assign D_13 = (A2_20 & B1_17) | (A1_23 & B1_17);
    assign B1_18 = B_19 | A_39 | B_20 | A_37;
    assign A3_12 = ~A_40 & ~A_41 & A_42 & A_43;
    assign A3_13 = ~A_41 & A_42 & A_40 & A_43;
    assign B1_19 = B_22 | A_45 | B_21 | A_44;
    assign B_22 = ~I | ~A_8;
    assign B1_20 = (I & A_8 & A3_14) | A_N_4;
    assign B1_21 = (I & A_8 & A3_15) | A_N_5;
    assign A3_15 = ~A_40 & ~A_42 & A_41 & A_43;
    assign B_23 = ~I | ~A_8;
    assign B1_22 = B_23 | A_50 | B_24 | A_49;
    assign A2_21 = ~I | ~A_8 | ~A_N_5 | ~A3_15;
    assign A2_22 = ~I | ~A_8 | ~A_N_4 | ~A3_14;
    assign D_17 = (A2_22 & B1_20) | (A1_24 & B1_20);
    assign A3_14 = ~A_43 & ~A_42 & A_41 & A_40;
    assign A2_23 = ~A_50 & ~B_23;
    assign A2_24 = ~I | ~A_8 | ~A_N_3 | ~A3_13;
    assign D_19 = (A2_23 & B1_22) | (A_47 & B1_22);
    assign B_24 = ~A_47;
    assign A_50 = ~A_41 | A_42 | A_40 | A_43;
    assign D_18 = (A2_21 & B1_21) | (A1_26 & B1_21);
    assign D_16 = (A2_24 & B1_23) | (A1_25 & B1_23);
    assign B1_23 = (I & A_8 & A3_13) | A_N_3;
    assign A2_20 = ~I | ~A_8 | ~A_N_2 | ~A3_12;
    assign A_45 = ~A_43 | A_42 | A_41 | A_40;
    assign A2_25 = ~I | ~A_8 | ~A_N_1 | ~A3_11;
    assign D_20 = (A2_27 & B1_24) | (A1_28 & B1_24);
    assign D_26 = (A2_26 & B1_18) | (A_52 & B1_18);
    assign A3_16 = ~A_41 & ~A_42 & A_40 & A_43;
    assign D_11 = (A2_25 & B1_16) | (A1_27 & B1_16);
    assign D_29 = (A2_28 & B1_19) | (A_53 & B1_19);
    assign A2_26 = ~A_39 & ~B_19;
    assign A_39 = ~A_42 | A_41 | A_40 | A_43;
    assign A3_11 = ~A_43 & ~A_41 & A_42 & A_40;
    assign B_20 = ~A_52;
    assign B_21 = ~A_53;
    assign B_2 = ~A_12;
    assign A2_27 = ~I | ~A_8 | ~A_N_6 | ~A3_16;
    assign B1_24 = (I & A_8 & A3_16) | A_N_6;
    assign A2_28 = ~A_45 & ~B_22;
    assign A2_1 = ~A_11 & ~B_3;
    assign B1_25 = (I & A_8 & A3_17) | A_N_7;
    assign D_31 = (A2_31 & B1_25) | (A1_31 & B1_25);
    assign A3_17 = ~A_43 & ~A_40 & ~A_41 & ~A_42;
    assign A2_31 = ~I | ~A_8 | ~A_N_7 | ~A3_17;
    assign B_3 = ~I | ~A_8;
    assign A_11 = ~A_40 | A_42 | A_41 | A_43;
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i3 (.CLK(clk), .D(D_11), .RESET_B(rst_n), .Q(A_N_1));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i4 (.CLK(clk), .D(D_12), .RESET_B(rst_n), .Q(A_37));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i5 (.CLK(clk), .D(D_13), .RESET_B(rst_n), .Q(A_N_2));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i14 (.CLK(clk), .D(D_15), .RESET_B(rst_n), .Q(A_44));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i15 (.CLK(clk), .D(D_2), .RESET_B(rst_n), .Q(A_12));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i18 (.CLK(clk), .D(D_16), .RESET_B(rst_n), .Q(A_N_3));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i19 (.CLK(clk), .D(D_17), .RESET_B(rst_n), .Q(A_N_4));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i20 (.CLK(clk), .D(D_18), .RESET_B(rst_n), .Q(A_N_5));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i21 (.CLK(clk), .D(D_19), .RESET_B(rst_n), .Q(A_47));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i23 (.CLK(clk), .D(D_20), .RESET_B(rst_n), .Q(A_N_6));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i37 (.CLK(clk), .D(D_22), .RESET_B(rst_n), .Q(A1_24));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i38 (.CLK(clk), .D(D_21), .RESET_B(rst_n), .Q(A_49));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i39 (.CLK(clk), .D(D_23), .RESET_B(rst_n), .Q(A1_26));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i49 (.CLK(clk), .D(D_24), .RESET_B(rst_n), .Q(A1_25));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i70 (.CLK(clk), .D(D_30), .RESET_B(rst_n), .Q(A1_27));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i71 (.CLK(clk), .D(D_26), .RESET_B(rst_n), .Q(A_52));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i72 (.CLK(clk), .D(D_14), .RESET_B(rst_n), .Q(A1_23));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i79 (.CLK(clk), .D(D_27), .RESET_B(rst_n), .Q(A1_28));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i80 (.CLK(clk), .D(D_29), .RESET_B(rst_n), .Q(A_53));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i81 (.CLK(clk), .D(D_1), .RESET_B(rst_n), .Q(A_10));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i85 (.CLK(clk), .D(D_31), .RESET_B(rst_n), .Q(A_N_7));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i93 (.CLK(clk), .D(D_34), .RESET_B(rst_n), .Q(A1_31));
endmodule

module cluster_type_1 (
    input [2:0] A2_7_bus,
    input [1:0] A_20_bus,
    input [13:0] A_3_bus,
    input A_32,
    input A_8,
    input [12:0] A1_12_bus,
    input A1_16,
    input A1_22,
    input B2_16,
    input B2_2,
    input I,
    input clk,
    input rst_n,
    output A_2,
    output A_5,
    output A_6,
    output A_7,
    output O_0_,
    output O_1_,
    output O_2_,
    output O_3_,
    output O_4_,
    output O_5_,
    output O_6_,
    output O_7_
);
    wire A1_1;
    wire A1_10;
    wire A1_17;
    wire A1_18;
    wire A1_19;
    wire A1_2;
    wire A1_20;
    wire A1_3;
    wire A1_35;
    wire A1_36;
    wire A1_37;
    wire A1_4;
    wire A1_6;
    wire A1_8;
    wire A1_9;
    wire A2_10;
    wire A2_11;
    wire A2_12;
    wire A2_14;
    wire A2_15;
    wire A2_16;
    wire A2_17;
    wire A2_18;
    wire A2_19;
    wire A2_2;
    wire A2_3;
    wire A2_33;
    wire A2_38;
    wire A2_39;
    wire A2_4;
    wire A2_40;
    wire A2_41;
    wire A2_42;
    wire A2_5;
    wire A2_9;
    wire A3_1;
    wire A3_10;
    wire A3_2;
    wire A3_21;
    wire A3_22;
    wire A3_23;
    wire A3_24;
    wire A3_3;
    wire A3_4;
    wire A3_6;
    wire A3_7;
    wire A3_8;
    wire A3_9;
    wire A_14;
    wire A_15;
    wire A_16;
    wire A_18;
    wire A_19;
    wire A_21;
    wire A_24;
    wire A_25;
    wire A_26;
    wire A_29;
    wire A_64;
    wire A_65;
    wire A_66;
    wire A_67;
    wire A_68;
    wire A_69;
    wire A_70;
    wire A_71;
    wire A_72;
    wire A_73;
    wire A_74;
    wire A_9;
    wire A_N_11;
    wire A_N_12;
    wire B1_10;
    wire B1_12;
    wire B1_13;
    wire B1_14;
    wire B1_15;
    wire B1_3;
    wire B1_31;
    wire B1_32;
    wire B1_33;
    wire B1_34;
    wire B1_35;
    wire B1_36;
    wire B1_37;
    wire B1_5;
    wire B1_6;
    wire B1_7;
    wire B1_8;
    wire B1_9;
    wire B2_18;
    wire B2_19;
    wire B2_20;
    wire B_1;
    wire B_10;
    wire B_11;
    wire B_12;
    wire B_13;
    wire B_15;
    wire B_16;
    wire B_17;
    wire B_18;
    wire B_32;
    wire B_35;
    wire B_36;
    wire B_37;
    wire B_38;
    wire B_39;
    wire B_4;
    wire B_40;
    wire B_41;
    wire B_42;
    wire B_43;
    wire B_44;
    wire B_45;
    wire B_46;
    wire B_5;
    wire B_6;
    wire B_7;
    wire B_8;
    wire B_9;
    wire C1;
    wire C1_1;
    wire C1_2;
    wire C1_3;
    wire D_3;
    wire D_39;
    wire D_4;
    wire D_40;
    wire D_41;
    wire D_42;
    wire D_43;
    wire D_44;
    wire D_45;
    wire D_46;
    wire D_8;
    wire D_9;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign D_8 = (A2_7_bus[1] & A_2 & A_5 & ~A_6) | (A2_7_bus[1] & ~A_2 & A_6) | (A2_7_bus[1] & ~A_5 & A_6) | (A2_7_bus[1] & A_2 & A_5 & A_7);
    assign D_3 = (A2_7_bus[1] & A_2 & A_6 & A_7) | (A2_7_bus[1] & ~A_5);
    assign D_9 = (A2_7_bus[1] & ~A_2 & A_5) | (A2_7_bus[1] & A_2 & ~A_5) | (A2_7_bus[1] & A_5 & A_6 & A_7);
    assign D_4 = (A2_7_bus[1] & A_2 & A_5 & A_6) | (A2_7_bus[1] & A_7);
    assign A3_1 = B_1 | A_9;
    assign A1_1 = (~A_14 & B_4) | (A_14 & ~B_4);
    assign B1_3 = (~A1_2 & ~A_15) | (~A2_2 & ~A_15);
    assign A2_3 = ~A_9 | ~B_1;
    assign B_5 = (A_16 & A_6) | (A_5 & A2_4);
    assign A_18 = A2_7_bus[1] & A1_3;
    assign A2_5 = ~A_19;
    assign A_21 = (~A1_4 & ~A_20_bus[1] & ~A_20_bus[0]) | (~A2_7_bus[0] & ~A_20_bus[1] & ~A_20_bus[0]);
    assign B_6 = (A3_2 & B1_5) | (A2_9 & B1_5) | (A1_6 & B1_5);
    assign O_0_ = A2_7_bus[1] & B_7 & A1_3;
    assign O_2_ = A2_7_bus[1] & B_8 & A1_3;
    assign A2_11 = (B1_6 & A1_12_bus[6]) | (A1_12_bus[5] & A2_10);
    assign O_7_ = A2_7_bus[1] & B_9 & A1_3;
    assign O_5_ = A2_7_bus[1] & B_10 & A1_3;
    assign B_7 = (A3_3 & B1_7) | (A2_11 & B1_7) | (A1_6 & B1_7);
    assign B_10 = (A3_4 & B1_8) | (A2_12 & B1_8) | (A1_6 & B1_8);
    assign A3_6 = (B1_9 & B2_2) | (A1_8 & A_24);
    assign A3_4 = (B1_9 & A_3_bus[11]) | (A1_1 & A_24);
    assign B_11 = (~A_25 & A_26) | (A_25 & ~A_26);
    assign A3_7 = (B1_9 & A_3_bus[12]) | (A1_9 & A_24);
    assign A3_2 = (B1_9 & A_3_bus[13]) | (A1_10 & A_24);
    assign B_8 = (A3_7 & B1_10) | (A2_14 & B1_10) | (A1_6 & B1_10);
    assign O_4_ = A2_7_bus[1] & B_12 & A1_3;
    assign O_3_ = A2_7_bus[1] & B_6 & A1_3;
    assign A1_3 = ~A_7 | ~A_6 | ~A_2 | ~A_5;
    assign A1_4 = ~A2_7_bus[2];
    assign B_13 = (A2_7_bus[0] & ~A_20_bus[1]) | (A2_7_bus[2] & ~A_20_bus[1]);
    assign A_29 = ~A_20_bus[0] & ~B_13;
    assign A_19 = ~A2_7_bus[0] | A_20_bus[1] | A2_7_bus[2] | A_20_bus[0];
    assign O_6_ = A2_7_bus[1] & B_15 & A1_3;
    assign B_16 = (A3_8 & B1_12) | (A2_15 & B1_12) | (A1_6 & B1_12);
    assign A2_14 = (B1_6 & A1_12_bus[9]) | (A1_12_bus[0] & A2_10);
    assign B1_13 = B_17 | A_24 | A_3_bus[0];
    assign A2_15 = (B1_6 & A1_12_bus[10]) | (A1_12_bus[1] & A2_10);
    assign A2_12 = (B1_6 & A1_12_bus[11]) | (A1_12_bus[2] & A2_10);
    assign A2_9 = (B1_6 & A1_12_bus[12]) | (A1_12_bus[3] & A2_10);
    assign A2_16 = (B1_6 & A1_12_bus[7]) | (A1_16 & A2_10);
    assign A1_6 = ~A_24 & ~B_17;
    assign A3_8 = (B1_9 & A_3_bus[7]) | (A1_17 & A_24);
    assign A_15 = ~A_18 | A_8;
    assign A_24 = ~A_29 & ~A2_5 & A_21;
    assign B1_9 = ~A_21 & ~A_29 & A2_5;
    assign A3_3 = (B1_9 & A_3_bus[8]) | (A1_18 & A_24);
    assign B1_7 = B_17 | A_24 | A_3_bus[1];
    assign A2_10 = ~A_21 & ~A2_5 & A_29;
    assign B1_6 = ~A_21 & ~A_29 & ~A2_5;
    assign B_12 = (A3_9 & B1_13) | (A2_16 & B1_13) | (A1_6 & B1_13);
    assign B_17 = (~A_29 & ~A_21) | (~A2_5 & ~A_21);
    assign B1_5 = B_17 | A_24 | A_3_bus[6];
    assign A2_17 = A_8 | A_18;
    assign A3_10 = (B1_9 & A_3_bus[9]) | (A1_19 & A_24);
    assign A3_9 = (B1_9 & A_3_bus[10]) | (A1_20 & A_24);
    assign A2_18 = (B1_6 & A1_12_bus[8]) | (A1_12_bus[4] & A2_10);
    assign O_1_ = A2_7_bus[1] & B_16 & A1_3;
    assign B1_8 = B_17 | A_24 | A_3_bus[2];
    assign B1_14 = B_17 | A_24 | A_32;
    assign B1_15 = B_17 | A_24 | A_3_bus[3];
    assign B_15 = (A3_10 & B1_15) | (A2_18 & B1_15) | (A1_6 & B1_15);
    assign B_9 = (A3_6 & B1_14) | (A2_19 & B1_14) | (A1_6 & B1_14);
    assign A2_19 = (B1_6 & B2_16) | (A1_22 & A2_10);
    assign C1 = ~A_15 & ~B_18;
    assign B1_10 = B_17 | A_24 | A_3_bus[4];
    assign B1_12 = B_17 | A_24 | A_3_bus[5];
    assign A2_33 = (~A_7 & ~B_32) | (A_7 & B_32);
    assign A_67 = (~A_66 & ~B_35) | (A_66 & B_35);
    assign B_32 = A_5 & A_2 & A_6;
    assign A1_10 = (~A_25 & B_36) | (A_25 & ~B_36);
    assign B1_31 = ~A_8 & ~B_37 & A_67;
    assign B1_32 = (~I & A_8) | (~A_67 & A_8);
    assign B1_33 = (A_5 & A_6) | A3_21 | A2_38;
    assign B_18 = (~A_64 & ~B_38) | (A_64 & B_38);
    assign D_46 = (A_69 & B1_34) | (A_8 & A_64) | C1_1;
    assign A1_35 = ~A_N_11 & B_39;
    assign B_38 = (~A_25 & A_69) | (A_25 & ~A_69);
    assign B1_35 = (~A_5 & ~A_70) | (~A2_38 & ~A_70) | (~A_5 & ~A3_22) | (~A2_38 & ~A3_22);
    assign D_42 = (B1_34 & A_65) | (A_8 & A_25) | C1_2;
    assign B2_18 = (B_39 & B_37) | (A_8 & A_9) | B1_34;
    assign D_40 = (A2_17 & B2_18) | (A2_17 & B1_31) | (A_25 & B2_18) | (A_25 & B1_31);
    assign C1_2 = (A2_2 & B1_3) | (A1_2 & B1_3);
    assign B_37 = (~A_68 & ~B_11) | (A_68 & B_11);
    assign A_N_11 = (~A_68 & B_1) | (A_68 & ~B_1);
    assign B_40 = (~A_26 & A_70) | (A_26 & ~A_70);
    assign B_1 = (~A_64 & ~A_66) | (A_64 & A_66);
    assign A1_9 = (~A_9 & ~B_41) | (A_9 & B_41);
    assign B_41 = (~A1_36 & ~A2_39) | ~B1_33;
    assign C1_3 = (~I & ~A_67) | ~B1_32;
    assign A2_2 = (~A_68 & A_65) | (A_68 & ~A_65);
    assign C1_1 = ~A_67 & ~A_15;
    assign A_71 = ~A_6 | ~A3_21;
    assign A2_40 = ~A_8 & A_67 & A_N_11;
    assign B2_19 = (~A_64 & ~A_72) | (A_64 & A_72);
    assign B_42 = (A_6 & A2_38 & A3_22) | B1_35;
    assign A3_23 = (A_8 & A_26) | B1_34;
    assign A_72 = (~A_9 & ~A_14) | (A_9 & A_14);
    assign A2_41 = (~A_72 & ~B_11) | (A_72 & B_11);
    assign D_43 = (A3_23 & A_9) | (A3_23 & A2_17) | (A2_40 & A_9) | (A2_40 & A2_17) | (A1_35 & A_9) | (A1_35 & A2_17);
    assign D_39 = (A_26 & B1_34) | (A_8 & A_68) | C1;
    assign A1_17 = (~A_73 & ~B_40) | (A_73 & B_40);
    assign B2_20 = ~A_2 | A_6 | A_5;
    assign A_66 = (~A_65 & ~A_25) | (A_65 & A_25);
    assign B_35 = (~A_14 & ~A_69) | (A_14 & A_69);
    assign A1_2 = (~A_9 & A_26) | (A_9 & ~A_26);
    assign A1_19 = (~A_64 & ~B_5) | (A_64 & B_5);
    assign A1_20 = (~A_65 & B_43) | (A_65 & ~B_43);
    assign A_73 = A2_4 | A_N_12 | A_74;
    assign B1_36 = (A_14 & B1_34) | (A_8 & A_65);
    assign A_16 = ~A_5 | A_2;
    assign B_4 = ~A_16 | ~B_44;
    assign B1_34 = ~A_18 & ~A_8;
    assign A3_21 = ~A_5 & A_2;
    assign B1_37 = (B1_34 & A_64) | (A_8 & A_14);
    assign D_41 = (A1_37 & A2_3 & A3_1) | B1_37;
    assign D_44 = (A1_37 & A2_41) | B1_36;
    assign A1_37 = ~A_8 & A_18;
    assign A_N_12 = ~A_5 & ~A_2;
    assign A2_4 = ~A_6 & ~A_7;
    assign A2_42 = ~A_2 | ~A_7;
    assign D_45 = (A2_17 & B2_19 & C1_3) | (A2_17 & A_15 & C1_3) | (A_68 & B2_19 & C1_3) | (A_68 & A_15 & C1_3);
    assign B_45 = (~A_71 & ~A_74) | (~A2_42 & ~A_74);
    assign B_44 = (A2_33 & B2_20) | (A_74 & A_70);
    assign A2_38 = ~A_7;
    assign A_74 = ~A_5 & ~A2_38;
    assign A3_22 = ~A_5 | ~A_2;
    assign B_43 = (A3_21 & A2_42) | (A_74 & A2_42) | (A_6 & A2_42);
    assign A1_36 = ~A_71;
    assign A1_18 = (~A_68 & ~B_45) | (A_68 & B_45);
    assign B_36 = (A3_24 & A2_39) | (A3_24 & B_46) | (A2_33 & A2_39) | (A2_33 & B_46) | (A1_36 & A2_39) | (A1_36 & B_46);
    assign A1_8 = (~A_69 & ~B_42) | (A_69 & B_42);
    assign A3_24 = ~A_6 & ~B_46;
    assign A_70 = A_6 | A_2;
    assign A2_39 = ~A_70 | ~A2_33;
    assign B_46 = ~A_N_12 & A3_22;
    assign B_39 = ~A_8 & ~A_67;
    sky130_fd_sc_hd__dfxtp_2 sky130_fd_sc_hd__dfxtp_2_i19 (.CLK(clk), .D(D_8), .Q(A_6));
    sky130_fd_sc_hd__dfxtp_2 sky130_fd_sc_hd__dfxtp_2_i20 (.CLK(clk), .D(D_3), .Q(A_5));
    sky130_fd_sc_hd__dfxtp_2 sky130_fd_sc_hd__dfxtp_2_i21 (.CLK(clk), .D(D_9), .Q(A_2));
    sky130_fd_sc_hd__dfxtp_2 sky130_fd_sc_hd__dfxtp_2_i22 (.CLK(clk), .D(D_4), .Q(A_7));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i76 (.CLK(clk), .D(D_39), .RESET_B(rst_n), .Q(A_26));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i77 (.CLK(clk), .D(D_40), .RESET_B(rst_n), .Q(A_25));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i78 (.CLK(clk), .D(D_41), .RESET_B(rst_n), .Q(A_64));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i79 (.CLK(clk), .D(D_42), .RESET_B(rst_n), .Q(A_65));
    sky130_fd_sc_hd__dfstp_2 sky130_fd_sc_hd__dfstp_2_i85 (.CLK(clk), .D(D_43), .SET_B(rst_n), .Q(A_9));
    sky130_fd_sc_hd__dfstp_2 sky130_fd_sc_hd__dfstp_2_i86 (.CLK(clk), .D(D_44), .SET_B(rst_n), .Q(A_14));
    sky130_fd_sc_hd__dfstp_2 sky130_fd_sc_hd__dfstp_2_i87 (.CLK(clk), .D(D_45), .SET_B(rst_n), .Q(A_68));
    sky130_fd_sc_hd__dfstp_2 sky130_fd_sc_hd__dfstp_2_i88 (.CLK(clk), .D(D_46), .SET_B(rst_n), .Q(A_69));
endmodule

module cluster_type_2 (
    input A_40,
    input A_41,
    input A_42,
    input A_43,
    input [3:0] A_94_bus,
    output [3:0] A_60_bus
);
    wire A0_14;
    wire A0_15;
    wire A0_16;
    wire A0_17;
    wire A0_18;
    wire A1_47;
    wire A1_48;
    wire A1_49;
    wire A1_50;
    wire A1_54;
    wire A1_56;
    wire A1_57;
    wire A1_62;
    wire A1_63;
    wire A1_64;
    wire A2_46;
    wire A2_47;
    wire A2_48;
    wire A2_49;
    wire A2_50;
    wire A2_51;
    wire A2_52;
    wire A2_53;
    wire A2_54;
    wire A2_55;
    wire A2_58;
    wire A2_59;
    wire A2_60;
    wire A2_61;
    wire A2_64;
    wire A2_65;
    wire A2_66;
    wire A2_67;
    wire A2_68;
    wire A2_69;
    wire A2_70;
    wire A2_71;
    wire A2_72;
    wire A2_73;
    wire A2_74;
    wire A2_75;
    wire A2_76;
    wire A2_77;
    wire A2_85;
    wire A2_86;
    wire A2_87;
    wire A2_88;
    wire A2_N;
    wire A3_32;
    wire A3_33;
    wire A3_34;
    wire A3_35;
    wire A3_40;
    wire A3_41;
    wire A3_42;
    wire A_102;
    wire A_103;
    wire A_104;
    wire A_105;
    wire A_106;
    wire A_107;
    wire A_108;
    wire A_109;
    wire A_110;
    wire A_111;
    wire A_112;
    wire A_113;
    wire A_114;
    wire A_115;
    wire A_117;
    wire A_118;
    wire A_119;
    wire A_122;
    wire A_123;
    wire A_124;
    wire A_125;
    wire A_126;
    wire A_138;
    wire A_139;
    wire A_140;
    wire A_141;
    wire A_142;
    wire A_143;
    wire A_144;
    wire A_145;
    wire A_146;
    wire A_147;
    wire A_148;
    wire A_N_15;
    wire A_N_20;
    wire B1_49;
    wire B1_50;
    wire B1_51;
    wire B1_52;
    wire B1_53;
    wire B1_54;
    wire B1_55;
    wire B1_57;
    wire B1_58;
    wire B1_59;
    wire B1_60;
    wire B1_64;
    wire B1_65;
    wire B1_66;
    wire B1_67;
    wire B1_68;
    wire B1_69;
    wire B1_70;
    wire B1_71;
    wire B1_72;
    wire B1_80;
    wire B1_81;
    wire B1_N;
    wire B1_N_1;
    wire B2_22;
    wire B2_23;
    wire B2_24;
    wire B_56;
    wire B_57;
    wire B_58;
    wire B_59;
    wire B_60;
    wire B_61;
    wire B_63;
    wire B_65;
    wire B_66;
    wire B_67;
    wire B_68;
    wire B_69;
    wire B_70;
    wire B_71;
    wire B_78;
    wire B_79;
    wire B_80;
    wire B_81;
    wire B_82;
    wire C1_10;
    wire C1_8;
    wire C1_9;
    wire C_11;
    wire C_12;
    wire C_13;
    wire C_14;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign B_56 = ~A_102 & ~A_103;
    assign B1_49 = ~A_104 & ~A2_46;
    assign A1_47 = ~A_105 & ~A_106;
    assign A_108 = (~A_107 & ~B_57) | (A_107 & B_57);
    assign A_110 = (~A_109 & A2_47) | (A_109 & ~A2_47);
    assign B_58 = (A0_14 & A_108 & C1_8) | (A1_48 & A_108 & C1_8);
    assign A1_49 = (A2_48 & A_108 & C1_9) | (A_110 & A_108 & C1_9) | (A1_47 & A_108 & C1_9);
    assign B_59 = (~A_42 & A_94_bus[3]) | (~A2_N & A_94_bus[3]) | (~A_42 & B1_50) | (~A2_N & B1_50);
    assign A2_49 = (~A_94_bus[0] & A_94_bus[3]) | (A_94_bus[0] & ~A_94_bus[3]);
    assign A_109 = (A_111 & A2_50) | B1_51;
    assign A2_51 = ~A_94_bus[2] | ~A2_49;
    assign B2_22 = (A_94_bus[1] & A_94_bus[3] & A_94_bus[2]) | A2_52;
    assign A2_N = (~A_94_bus[1] & ~B1_52) | (~A2_49 & ~B1_52);
    assign A_112 = ~A_94_bus[0] | ~A_94_bus[3];
    assign A_113 = ~A_94_bus[1] & ~A2_51;
    assign B1_53 = (A0_14 & ~A2_53) | (A_106 & A2_53);
    assign B_60 = ~A_114;
    assign A2_54 = (~A_106 & ~A1_50) | (~B1_54 & ~A_115);
    assign A_106 = (~A_111 & ~B_61) | (A_111 & B_61);
    assign B1_N = (A_106 & A2_55) | A_110 | B1_55;
    assign A2_59 = (~A_102 & ~A2_58) | ~A_110;
    assign A_60_bus[2] = (A2_60 & B1_57 & B1_58) | (A1_54 & B1_57 & B1_58);
    assign B1_60 = (B1_59 & B2_23) | (A_110 & A2_54) | A_117;
    assign B_61 = (~A_118 & ~B_59) | (A_118 & B_59);
    assign A_117 = (~A_119 & ~B_63) | (A_119 & B_63);
    assign A_115 = (~A_107 & B_57) | (A_107 & ~B_57);
    assign A1_54 = (~A_119 & B_63) | (A_119 & ~B_63);
    assign C1_10 = C_11 | B_58 | A_117;
    assign A_60_bus[3] = (A2_61 & B1_60 & B1_58) | (A1_54 & B1_60 & B1_58);
    assign A2_47 = ~A_122 & ~B_65;
    assign A2_50 = ~A_118 | ~B_59;
    assign A_107 = (A_109 & A2_47) | A_122;
    assign B1_64 = (A_110 & A2_64) | A_108 | B1_53;
    assign A2_65 = (~A_94_bus[1] & ~A2_51) | (~B1_65 & ~B2_22);
    assign B_63 = (A_123 & A2_52) | B1_66;
    assign B_65 = A_124 & A2_66 & B1_67;
    assign B1_67 = C_12 | A2_52 | A_113;
    assign B1_58 = ~A_125 & ~B_66;
    assign B1_68 = A_108 & B_67 & C_13;
    assign A_119 = (~A_107 & ~A_N_15) | (~A2_65 & ~A_N_15);
    assign B1_51 = ~A_118 & ~B_59;
    assign B_57 = ~A_N_15 & A2_65;
    assign C_12 = A_112 & A2_51 & B_68;
    assign A_125 = ~A_119 & ~B_63;
    assign A2_52 = ~A_112 & ~B_68;
    assign A_123 = ~A_94_bus[1] | ~A_94_bus[3];
    assign B1_66 = (~A_94_bus[2] & ~A2_52) | (~A_123 & ~A2_52);
    assign B1_65 = (~A_94_bus[1] & ~A_94_bus[3]) | (~A_94_bus[2] & ~A_94_bus[3]);
    assign A_122 = (~A_124 & ~B1_67) | (~A2_66 & ~B1_67);
    assign A_60_bus[1] = (A2_67 & B1_69 & B1_58) | (A1_54 & B1_69 & B1_58);
    assign A_118 = (~A_41 & ~B_69) | (A_41 & B_69);
    assign B_69 = (~A_123 & ~B_70) | (A_123 & B_70);
    assign B_68 = (~A_94_bus[1] & ~A_94_bus[2]) | (A_94_bus[1] & A_94_bus[2]);
    assign B_70 = (~A_94_bus[2] & A2_49) | (A_94_bus[2] & ~A2_49);
    assign A_124 = ~B_70 | A_123;
    assign A2_66 = ~A_41 | ~B_69;
    assign A2_61 = (~A_115 & ~A2_68) | ~B1_70;
    assign A0_15 = B_71 | A_126;
    assign C_11 = (~A1_48 & ~A_108) | (~A2_69 & ~A_108);
    assign A2_67 = (A_115 & A2_70) | B1_68;
    assign A2_71 = A_106 & B_60 & A3_32;
    assign C_13 = (~A0_14 & ~A2_71) | ~A_110;
    assign A2_60 = (A0_16 & ~A_115) | (A1_56 & A_115);
    assign A2_73 = (A_115 & A2_72 & A3_33) | A1_54;
    assign A2_74 = (A0_15 & ~A_110) | (A1_57 & A_110);
    assign A_60_bus[0] = (A2_73 & B1_58 & C1_10) | (A1_49 & B1_58 & C1_10);
    assign B1_69 = (~A_115 & ~A2_74) | ~B1_64 | ~A1_54;
    assign A0_16 = (A3_34 & B1_71) | (A3_34 & B1_49) | (A2_48 & B1_71) | (A2_48 & B1_49) | (A_110 & B1_71) | (A_110 & B1_49);
    assign B2_23 = (~A_115 & ~A_110) | (~A2_75 & ~A_110);
    assign B1_59 = B_56 | A_115;
    assign B1_57 = (A_115 & A2_76) | A_117 | B1_72;
    assign A2_68 = (A3_35 & B2_24) | (A3_35 & B1_71) | (A2_48 & B2_24) | (A2_48 & B1_71) | (A_110 & B2_24) | (A_110 & B1_71);
    assign A2_70 = (A_110 & A2_77) | ~B1_N;
    assign A_139 = (~A_138 & A_N_20) | (A_138 & ~A_N_20);
    assign B1_80 = (A2_53 & A_140) | (A2_53 & A3_40) | (A_102 & A_140) | (A_102 & A3_40);
    assign C_14 = (A_139 & A_106 & A_105) | (A_141 & A_106 & A_105);
    assign A_N_15 = ~A_94_bus[0] & ~A_94_bus[1] & A_94_bus[3] & A_94_bus[2];
    assign A_142 = (~A_138 & ~A_N_20) | (A_138 & A_N_20);
    assign A_102 = (~A_111 & B_61) | (A_111 & ~B_61);
    assign A2_69 = C_14 | A0_14 | A_110;
    assign A1_57 = (A_143 & A_106) | (A1_50 & A0_14);
    assign A3_34 = ~A_106 & ~A0_17;
    assign C1_9 = ~A_110 | ~B_78;
    assign A0_14 = ~A_106 & ~A_104;
    assign A_126 = ~A_102 & ~A2_64;
    assign B1_54 = A_143 | A_102 | A_141;
    assign A1_63 = A1_62 | B_79 | A_141;
    assign A2_58 = ~A_143;
    assign A2_46 = ~A_106 | ~A1_50;
    assign A0_18 = (A2_46 & A2_85) | (A_141 & A2_85);
    assign A3_40 = A2_64 | A_106;
    assign A2_72 = (A_142 & A2_85) | ~B1_N_1;
    assign A1_64 = (A_102 & A_103 & A3_32) | A2_86;
    assign B_80 = (~A_141 & ~A_102 & ~A_139) | ~A_105;
    assign A2_76 = (A_110 & A2_46 & A3_40) | (B1_80 & B1_N_1);
    assign A2_53 = ~A2_64 | A2_86;
    assign B_71 = (A_114 & A2_64) | (A_102 & A2_64);
    assign B1_71 = (~A_106 & ~A1_62 & ~A2_58) | ~A_110;
    assign B_78 = (A0_17 & ~A_102) | (A1_63 & A_102);
    assign A2_75 = (A2_55 & ~A2_77) | (A_106 & ~A2_77);
    assign A3_33 = ~A_110 | ~B_80;
    assign A3_35 = (~A_106 & ~A0_17) | (~A2_86 & ~A0_17);
    assign B1_81 = (A2_87 & A3_40) | (A_102 & A3_40);
    assign A2_85 = B_79 | A_106;
    assign B1_55 = (A_143 & A_102) | (A_141 & A_102);
    assign C1_8 = A_126 | B_56 | A_110;
    assign A_143 = B_79 | A_139;
    assign A2_55 = ~A_138 | ~A_114;
    assign A_144 = ~A_43 | ~A2_88;
    assign B1_70 = B1_55 | A1_63 | A_108 | A_110;
    assign B_66 = (A_94_bus[1] & A_94_bus[3] & A_94_bus[2]) | (A_94_bus[0] & A_94_bus[3] & A_94_bus[2]);
    assign A3_41 = ~A_N_20 & B_81;
    assign A_104 = ~A_142 & ~B_79;
    assign B_81 = ~A_145 | ~B_82;
    assign B_67 = (A_138 & A_110 & A3_41) | A2_71 | A0_14;
    assign B1_N_1 = (~A_102 & ~A_110) | (~A_104 & ~A_110);
    assign A2_87 = A_103 & A3_32;
    assign A3_42 = (~A_42 & A2_N) | (A_42 & ~A2_N);
    assign A2_88 = (~A_94_bus[0] & A_94_bus[1]) | (A_94_bus[0] & ~A_94_bus[1]);
    assign A_111 = (A_43 & A2_88 & A3_42) | (A_138 & A_N_20);
    assign A_145 = (~A_43 & ~A2_88) | (A_43 & A2_88);
    assign A1_56 = (A0_18 & ~A_110) | (A1_64 & A_110);
    assign B1_72 = (A2_59 & A_110 & A_108) | (A2_59 & B1_81 & A_108) | (A1_62 & A_110 & A_108) | (A1_62 & B1_81 & A_108);
    assign A_138 = (~A_144 & ~A3_42) | (A_144 & A3_42);
    assign A_146 = A_40 & A_94_bus[0];
    assign A2_48 = A_106 & A_142 & A2_86;
    assign A_114 = ~A_147 & ~B_81;
    assign A_105 = ~A_138 | ~A_141;
    assign A_141 = ~A_145 & ~A_148;
    assign A1_50 = ~A_142 | ~B_79;
    assign A_148 = A_147 | A_146;
    assign B_82 = ~A_40 | ~A_94_bus[0];
    assign A0_17 = B_79 | A_142 | A_141;
    assign A2_64 = A3_41 | A_139;
    assign A1_48 = ~A_110 | ~A2_46;
    assign A2_86 = A_148 & A3_41;
    assign B1_50 = ~A_94_bus[0] | ~A_94_bus[1];
    assign A_147 = ~A_40 & ~A_94_bus[0];
    assign B1_52 = ~A_94_bus[1] & ~A_94_bus[3];
    assign A_103 = ~A_138 | ~A3_41;
    assign A2_77 = ~A_105 & ~A_102;
    assign A_140 = ~A_146 & ~A_147;
    assign B2_24 = ~A_102 & ~A_104;
    assign A3_32 = ~A_148 | ~A_142;
    assign A1_62 = ~A_142 & ~A_114;
    assign B_79 = ~A_140 & ~A3_41;
    assign A_N_20 = ~A_145 & ~B_82;
endmodule

module cluster_type_3 (
    input [10:0] A_48_bus,
    input [1:0] A1_38_bus,
    input A_8,
    input B1_42,
    input I,
    input clk,
    input rst_n,
    output [1:0] A_23_bus
);
    wire A0;
    wire A0_1;
    wire A0_10;
    wire A0_11;
    wire A0_2;
    wire A0_3;
    wire A0_4;
    wire A0_5;
    wire A0_6;
    wire A0_7;
    wire A0_8;
    wire A0_9;
    wire A_79;
    wire A_80;
    wire B_49;
    wire C_6;
    wire D_52;
    wire D_53;
    wire D_54;
    wire D_55;
    wire D_56;
    wire D_57;
    wire D_58;
    wire D_59;
    wire D_60;
    wire D_61;
    wire D_62;
    wire D_63;
    wire D_64;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign A_23_bus[0] = ~A_80;
    assign D_52 = (~A_8 & A0) | (A_8 & A0_7);
    assign D_53 = (~A_8 & A0_1) | (A_8 & I);
    assign D_54 = (~A_8 & A0_3) | (A_8 & A0_6);
    assign D_55 = (~A_8 & A0_4) | (A_8 & A0_5);
    assign D_61 = (~A_8 & A0_2) | (A_8 & A0_9);
    assign D_59 = (A_8 & A0_9 & B1_42 & I) | (A_8 & A0_8 & A1_38_bus[0] & I) | (A1_38_bus[1] & A_8 & A0_2 & I) | (A1_38_bus[1] & A_8 & A0_1 & I) | A_80;
    assign D_62 = (~A_8 & A0_9) | (A_8 & A0_8);
    assign D_58 = (~A_8 & A0_7) | (A_8 & A0_3);
    assign D_63 = (~A_8 & A0_11) | (A_8 & A0_10);
    assign D_64 = (~A_8 & A0_8) | (A_8 & A0_11);
    assign D_57 = (~A_8 & A0_6) | (A_8 & A0_4);
    assign D_56 = (~A_8 & A0_5) | (A_8 & A0_1);
    assign D_60 = (~A_8 & A0_10) | (A_8 & A0);
    assign B_49 = A_48_bus[2] & A_48_bus[5] & A_48_bus[8] & A_48_bus[10];
    assign A_23_bus[1] = A_79 & B_49 & C_6;
    assign A_79 = A_48_bus[1] & A_48_bus[4] & A_48_bus[6] & A_48_bus[9];
    assign C_6 = A_48_bus[0] & A_48_bus[3] & A_48_bus[7];
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i0 (.CLK(clk), .D(D_52), .RESET_B(rst_n), .Q(A0));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i2 (.CLK(clk), .D(D_53), .RESET_B(rst_n), .Q(A0_1));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i3 (.CLK(clk), .D(D_54), .RESET_B(rst_n), .Q(A0_3));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i9 (.CLK(clk), .D(D_55), .RESET_B(rst_n), .Q(A0_4));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i17 (.CLK(clk), .D(D_61), .RESET_B(rst_n), .Q(A0_2));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i18 (.CLK(clk), .D(D_59), .RESET_B(rst_n), .Q(A_80));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i19 (.CLK(clk), .D(D_62), .RESET_B(rst_n), .Q(A0_9));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i21 (.CLK(clk), .D(D_58), .RESET_B(rst_n), .Q(A0_7));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i22 (.CLK(clk), .D(D_63), .RESET_B(rst_n), .Q(A0_11));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i23 (.CLK(clk), .D(D_64), .RESET_B(rst_n), .Q(A0_8));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i25 (.CLK(clk), .D(D_57), .RESET_B(rst_n), .Q(A0_6));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i27 (.CLK(clk), .D(D_56), .RESET_B(rst_n), .Q(A0_5));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i32 (.CLK(clk), .D(D_60), .RESET_B(rst_n), .Q(A0_10));
endmodule

module cluster_type_4 (
    input A_2,
    input A_5,
    input A_6,
    input A_7,
    input A1_55,
    output [13:0] A_3_bus
);
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign A_3_bus[0] = (~A_2 & ~A_6 & ~A_7) | (~A_5 & ~A_6 & ~A_7);
    assign A_3_bus[1] = (A_2 & ~A_5 & ~A_7) | (A_6 & ~A_7);
    assign A_3_bus[2] = A_2 & A_5 & ~A_6 & ~A_7;
    assign A_3_bus[3] = (~A_2 & ~A_5 & ~A_6) | (~A_2 & ~A_7) | (~A_5 & ~A_7) | (A_6 & ~A_7);
    assign A_3_bus[4] = (~A_2 & A_5 & A_6 & ~A_7) | (~A_2 & ~A_5 & ~A_6);
    assign A_3_bus[5] = (~A_2 & ~A_5 & ~A_6 & A_7) | (~A_2 & A_5 & ~A_7);
    assign A_3_bus[6] = (~A_2 & ~A_5 & ~A_6 & A_7) | (A_2 & ~A_5 & ~A_6 & ~A_7) | (A_2 & A_5 & A_6 & ~A_7);
    assign A_3_bus[7] = (A_2 & ~A_5 & ~A_6 & ~A_7) | (~A_2 & A_6 & ~A_7) | (~A_2 & A_6 & A1_55) | (A_5 & ~A_6 & A_7) | (~A_2 & A_5 & ~A_6) | (A_2 & ~A_6 & ~A_7 & ~A1_55);
    assign A_3_bus[8] = (~A_2 & A_5 & ~A_7) | (A_2 & ~A_5 & ~A_6) | (A_5 & ~A_6 & A_7);
    assign A_3_bus[9] = (~A_2 & ~A_5) | (~A_2 & ~A_7) | (~A_5 & ~A_7) | (~A_6 & A_7);
    assign A_3_bus[10] = (A_2 & ~A_5 & A_6 & ~A_7) | (~A_2 & ~A_6 & ~A_7) | (~A_5 & ~A_6 & A_7) | (A_2 & ~A_5 & A_7 & A1_55);
    assign A_3_bus[11] = A_2 & A_5 & ~A_7;
    assign A_3_bus[12] = (~A_2 & ~A_6) | (~A_5 & ~A_6) | (~A_2 & ~A_7) | (~A_5 & ~A_7);
    assign A_3_bus[13] = (A_2 & ~A_5 & ~A_6 & ~A_7) | (~A_2 & A_5 & ~A_6 & A_7) | (~A_2 & ~A_5 & A_6) | (~A_2 & A_6 & ~A_7);
endmodule

module cluster_type_5 (
    input A_8,
    input I,
    input clk,
    input rst_n,
    output [1:0] A_20_bus,
    output B_14
);
    wire A1_39;
    wire A1_40;
    wire A1_41;
    wire A2_45;
    wire A3_26;
    wire A_81;
    wire A_82;
    wire A_83;
    wire A_84;
    wire A_85;
    wire A_86;
    wire A_92;
    wire A_N_13;
    wire A_N_14;
    wire B1_44;
    wire B_52;
    wire D_65;
    wire D_66;
    wire D_67;
    wire D_69;
    wire D_73;
    wire D_74;
    wire D_75;
    wire D_76;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign A_20_bus[0] = ~A_81 & ~A_82 & ~A_83 & ~A_85 & ~A_86 & ~A_92 & ~A1_39 & ~A_N_14;
    assign B_14 = ~A_81 & ~A_82 & ~A_83 & ~A_85 & A_86 & A_92 & ~A1_39 & A_N_14;
    assign A_20_bus[1] = A_81 & ~A_82 & A_83 & A_85 & A_86 & ~A_92 & A1_39 & ~A_N_14;
    assign D_73 = (A_8 & A_81 & A_92 & ~A1_39 & A_N_14 & I) | (~A_8 & A1_39) | (~A_81 & A1_39) | (~A_92 & A1_39) | (A1_39 & ~A_N_14) | (A1_39 & ~I);
    assign D_65 = (A_8 & A_81 & A_92 & ~A_N_14 & I) | (~A_8 & A_N_14) | (~A_81 & A_N_14) | (~A_92 & A_N_14) | (A_N_14 & ~I);
    assign D_74 = (A_8 & A_81 & ~A_92 & I) | (~A_8 & A_92) | (~A_81 & A_92) | (A_92 & ~I);
    assign D_66 = (A_8 & ~A_81 & I) | (~A_8 & A_81) | (A_81 & ~I);
    assign A_N_13 = A_83 & A1_40 & A_84 & A3_26;
    assign D_67 = ~A_N_13 & B_52;
    assign D_69 = (A2_45 & B1_44) | (A1_41 & B1_44);
    assign A1_41 = ~A_86 | ~A_85;
    assign B_52 = (A1_40 & A_84 & A3_26) | A_83;
    assign B1_44 = (A_86 & A_84 & A3_26) | A_85;
    assign A1_40 = A_86 & A_85;
    assign A2_45 = ~A_84 | ~A3_26;
    assign D_75 = (~A_82 & A_N_13) | (A_82 & ~A_N_13);
    assign A_84 = A_81 & I & A_8;
    assign D_76 = (~A_86 & ~A2_45) | (A_86 & A2_45);
    assign A3_26 = A_92 & A_N_14 & A1_39;
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i17 (.CLK(clk), .D(D_73), .RESET_B(rst_n), .Q(A1_39));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i19 (.CLK(clk), .D(D_65), .RESET_B(rst_n), .Q(A_N_14));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i21 (.CLK(clk), .D(D_74), .RESET_B(rst_n), .Q(A_92));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i23 (.CLK(clk), .D(D_66), .RESET_B(rst_n), .Q(A_81));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i24 (.CLK(clk), .D(D_75), .RESET_B(rst_n), .Q(A_82));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i29 (.CLK(clk), .D(D_69), .RESET_B(rst_n), .Q(A_85));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i30 (.CLK(clk), .D(D_76), .RESET_B(rst_n), .Q(A_86));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i31 (.CLK(clk), .D(D_67), .RESET_B(rst_n), .Q(A_83));
endmodule

module cluster_type_6 (
    input A_2,
    input A_5,
    input A_6,
    input A_7,
    output [12:0] A1_12_bus
);
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign A1_12_bus[0] = (A_2 & ~A_5 & ~A_7) | (A_2 & A_6 & ~A_7);
    assign A1_12_bus[1] = (A_2 & A_6 & ~A_7) | (~A_5 & ~A_7);
    assign A1_12_bus[2] = A_2 & A_5 & ~A_6 & ~A_7;
    assign A1_12_bus[3] = (~A_2 & A_5 & ~A_6 & ~A_7) | (A_2 & ~A_5 & A_6 & ~A_7);
    assign A1_12_bus[4] = (~A_2 & ~A_7) | (~A_5 & ~A_7) | (A_6 & ~A_7);
    assign A1_12_bus[5] = (A_2 & ~A_5 & ~A_6 & ~A_7) | (~A_2 & A_5 & ~A_7) | (A_5 & A_6 & ~A_7);
    assign A1_12_bus[6] = (~A_2 & ~A_5 & ~A_6) | (~A_2 & ~A_6 & ~A_7) | (A_2 & A_6 & ~A_7) | (~A_2 & ~A_5 & ~A_7);
    assign A1_12_bus[7] = (~A_2 & ~A_5 & ~A_6 & A_7) | (~A_5 & A_6 & ~A_7) | (A_2 & ~A_6 & ~A_7);
    assign A1_12_bus[8] = (~A_2 & ~A_5 & ~A_6) | (~A_5 & ~A_7) | (~A_6 & ~A_7) | (A_2 & ~A_7);
    assign A1_12_bus[9] = (~A_2 & ~A_6 & ~A_7) | (A_5 & ~A_6 & ~A_7);
    assign A1_12_bus[10] = A_2 & A_6 & ~A_7;
    assign A1_12_bus[11] = ~A_2 & A_5 & A_6 & ~A_7;
    assign A1_12_bus[12] = (~A_2 & ~A_5 & ~A_6 & A_7) | (~A_2 & ~A_5 & A_6 & ~A_7) | (~A_2 & A_5 & ~A_6 & ~A_7) | (A_2 & A_5 & A_6 & ~A_7);
endmodule

module cluster_type_7 (
    input A_40,
    input A_41,
    input A_42,
    input A_43,
    input A_75,
    input A_8,
    input I,
    input clk,
    input rst_n,
    output A_28,
    output [1:0] A1_38_bus
);
    wire A_88;
    wire A_90;
    wire A_91;
    wire D_70;
    wire D_71;
    wire D_72;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign A_28 = ~A_90;
    assign A1_38_bus[1] = A_43 | A_42 | A_41 | A_40;
    assign A1_38_bus[0] = ~A_41 | ~A_43 | A_42 | A_40;
    assign D_70 = (~A_75 & A_8 & A_91 & I) | (~A_75 & A_88) | (~A_8 & A_88);
    assign D_71 = A_90 | (A_75 & A_8 & ~A_88 & ~A_91) | (A_75 & A_8 & A_91 & ~I) | (A_75 & A_8 & A_88 & I);
    assign D_72 = (~A_75 & A_8 & ~A_91 & I) | (~A_75 & A_91 & ~I) | (~A_8 & A_91) | (~A_75 & A_8 & A_88 & I);
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i1 (.CLK(clk), .D(D_70), .RESET_B(rst_n), .Q(A_88));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i3 (.CLK(clk), .D(D_71), .RESET_B(rst_n), .Q(A_90));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i4 (.CLK(clk), .D(D_72), .RESET_B(rst_n), .Q(A_91));
endmodule

module cluster_type_8 (
    input A_75,
    input A_8,
    input clk,
    input rst_n,
    output [3:0] A_94_bus,
    output A2_43
);
    wire D_77;
    wire D_78;
    wire D_79;
    wire D_80;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign A2_43 = ~A_94_bus[0] & A_94_bus[1] & A_94_bus[2] & ~A_94_bus[3];
    assign D_77 = (A_75 & A_8 & A_94_bus[0] & A_94_bus[1] & ~A_94_bus[2] & A_94_bus[3]) | (~A_94_bus[0] & A_94_bus[2] & A_94_bus[3]) | (A_94_bus[0] & A_94_bus[2] & ~A_94_bus[3]) | (~A_75 & A_94_bus[2]) | (~A_8 & A_94_bus[2]) | (~A_94_bus[1] & A_94_bus[2]);
    assign D_78 = (A_75 & A_8 & A_94_bus[0] & A_94_bus[1] & ~A_94_bus[3]) | (~A_75 & A_94_bus[3]) | (~A_8 & A_94_bus[3]) | (~A_94_bus[0] & A_94_bus[3]) | (~A_94_bus[1] & A_94_bus[3]);
    assign D_79 = (A_75 & A_8 & ~A_94_bus[0] & ~A_94_bus[1]) | (A_75 & A_8 & ~A_94_bus[0] & ~A_94_bus[2]) | (A_75 & A_8 & ~A_94_bus[0] & A_94_bus[3]) | (~A_75 & A_94_bus[0]) | (~A_8 & A_94_bus[0]);
    assign D_80 = (A_75 & A_8 & A_94_bus[0] & ~A_94_bus[1]) | (~A_94_bus[0] & A_94_bus[1] & ~A_94_bus[2]) | (~A_94_bus[0] & A_94_bus[1] & A_94_bus[3]) | (~A_75 & A_94_bus[1]) | (~A_8 & A_94_bus[1]);
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i2 (.CLK(clk), .D(D_77), .RESET_B(rst_n), .Q(A_94_bus[2]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i3 (.CLK(clk), .D(D_78), .RESET_B(rst_n), .Q(A_94_bus[3]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i6 (.CLK(clk), .D(D_79), .RESET_B(rst_n), .Q(A_94_bus[0]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i10 (.CLK(clk), .D(D_80), .RESET_B(rst_n), .Q(A_94_bus[1]));
endmodule

module cluster_type_9 (
    input A_8,
    input clk,
    input rst_n,
    output A_40,
    output A_41,
    output A_42,
    output A_43,
    output A_75
);
    wire D_48;
    wire D_49;
    wire D_50;
    wire D_51;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign A_75 = ~A_40 & A_41 & ~A_42 & A_43;
    assign D_48 = (A_40 & ~A_42 & A_43 & A_8) | (~A_40 & A_42) | (A_42 & ~A_43) | (A_42 & ~A_8);
    assign D_49 = (A_40 & ~A_41 & A_42 & A_43 & A_8) | (~A_40 & A_41 & A_42) | (A_40 & A_41 & ~A_42) | (A_41 & ~A_43) | (A_41 & ~A_8);
    assign D_50 = (~A_40 & ~A_41 & A_8) | (~A_40 & ~A_43 & A_8) | (~A_40 & A_42 & A_8) | (A_40 & ~A_8);
    assign D_51 = (~A_40 & ~A_41 & A_43) | (~A_40 & A_42 & A_43) | (A_40 & ~A_43 & A_8) | (A_43 & ~A_8);
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i0 (.CLK(clk), .D(D_48), .RESET_B(rst_n), .Q(A_42));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i2 (.CLK(clk), .D(D_49), .RESET_B(rst_n), .Q(A_41));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i3 (.CLK(clk), .D(D_50), .RESET_B(rst_n), .Q(A_40));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i9 (.CLK(clk), .D(D_51), .RESET_B(rst_n), .Q(A_43));
endmodule

module cluster_type_10 (
    input [1:0] A_23_bus,
    input A_27,
    input A_28,
    input B_14,
    input C,
    input clk,
    input rst_n,
    output [2:0] A2_7_bus
);
    wire D_5;
    wire D_6;
    wire D_7;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign D_5 = A_27 | A2_7_bus[1];
    assign D_6 = (~A2_7_bus[1] & ~A_23_bus[0] & A_27 & A_28 & B_14 & C & A_23_bus[1]) | (~A_27 & A2_7_bus[0]) | (A2_7_bus[1] & A2_7_bus[0]);
    assign D_7 = (~A2_7_bus[1] & A_23_bus[0] & A_27 & A_28 & B_14 & C & A_23_bus[1]) | (~A_27 & A2_7_bus[2]) | (A2_7_bus[1] & A2_7_bus[2]);
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i0 (.CLK(clk), .D(D_5), .RESET_B(rst_n), .Q(A2_7_bus[1]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i1 (.CLK(clk), .D(D_6), .RESET_B(rst_n), .Q(A2_7_bus[0]));
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i2 (.CLK(clk), .D(D_7), .RESET_B(rst_n), .Q(A2_7_bus[2]));
endmodule

module cluster_type_11 (
    input [10:0] A_59_bus,
    output C
);
    wire A_99;
    wire B_53;
    wire C_8;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign C = A_99 & B_53 & C_8;
    assign A_99 = A_59_bus[1] & A_59_bus[4] & A_59_bus[6] & A_59_bus[9];
    assign C_8 = A_59_bus[0] & A_59_bus[3] & A_59_bus[7];
    assign B_53 = A_59_bus[2] & A_59_bus[5] & A_59_bus[8] & A_59_bus[10];
endmodule

module cluster_type_12 (
    input A_75,
    input A2_43,
    input clk,
    input enable,
    input rst_n,
    output A_27,
    output A_8
);
    wire D_47;
    // combinational logic flattened via z3 (see chip_manipulation.py)
    assign A_8 = ~A_27 & enable;
    assign D_47 = (A_75 & A2_43 & enable) | A_27;
    sky130_fd_sc_hd__dfrtp_2 sky130_fd_sc_hd__dfrtp_2_i0 (.CLK(clk), .D(D_47), .RESET_B(rst_n), .Q(A_27));
endmodule

module puzzle (
    input I,
    input clk,
    input enable,
    input rst_n,
    output O_0_,
    output O_1_,
    output O_2_,
    output O_3_,
    output O_4_,
    output O_5_,
    output O_6_,
    output O_7_,
    output success
);
    wire A_17;
    wire A_2;
    wire A_27;
    wire A_28;
    wire A_32;
    wire A_40;
    wire A_41;
    wire A_42;
    wire A_43;
    wire A_5;
    wire A_6;
    wire A_60;
    wire A_61;
    wire A_7;
    wire A_75;
    wire A_8;
    wire A1_16;
    wire A1_22;
    wire A1_55;
    wire A2_43;
    wire A2_7;
    wire A_N_10;
    wire B_14;
    wire B_31;
    wire B1_42;
    wire B2_16;
    wire B2_2;
    wire C;
    wire [1:0] A_20_bus;
    wire [13:0] A_3_bus;
    wire [12:0] A1_12_bus;
    wire [3:0] A_94_bus;
    wire [10:0] A_48_bus;
    wire [10:0] A_100_bus;
    wire [1:0] A1_38_bus;
    wire [1:0] A_23_bus;
    cluster_type_1 cluster_type_1_i0 (.A2_7_bus({success, A_17, A2_7}), .A_20_bus(A_20_bus), .A_3_bus(A_3_bus), .A_32(A_32), .A_8(A_8), .A1_12_bus(A1_12_bus), .A1_16(A1_16), .A1_22(A1_22), .B2_16(B2_16), .B2_2(B2_2), .I(I), .clk(clk), .rst_n(rst_n), .A_2(A_2), .A_5(A_5), .A_6(A_6), .A_7(A_7), .O_0_(O_0_), .O_1_(O_1_), .O_2_(O_2_), .O_3_(O_3_), .O_4_(O_4_), .O_5_(O_5_), .O_6_(O_6_), .O_7_(O_7_));
    cluster_type_2 cluster_type_2_i1 (.A_40(A_40), .A_41(A_41), .A_42(A_42), .A_43(A_43), .A_94_bus(A_94_bus), .A_60_bus({B_31, A_N_10, A_61, A_60}));
    cluster_type_0 cluster_type_0_i2 (.A_40(A_40), .A_41(A_41), .A_42(A_42), .A_43(A_43), .A_8(A_8), .I(I), .clk(clk), .rst_n(rst_n), .A_48_bus(A_48_bus));
    cluster_type_0 cluster_type_0_i3 (.A_40(A_60), .A_41(A_N_10), .A_42(B_31), .A_43(A_61), .A_8(A_8), .I(I), .clk(clk), .rst_n(rst_n), .A_48_bus(A_100_bus));
    cluster_type_3 cluster_type_3_i4 (.A_48_bus(A_48_bus), .A1_38_bus(A1_38_bus), .A_8(A_8), .B1_42(B1_42), .I(I), .clk(clk), .rst_n(rst_n), .A_23_bus(A_23_bus));
    cluster_type_4 cluster_type_4_i5 (.A_2(A_2), .A_5(A_5), .A_6(A_6), .A_7(A_7), .A1_55(A1_55), .A_3_bus(A_3_bus));
    cluster_type_5 cluster_type_5_i6 (.A_8(A_8), .I(I), .clk(clk), .rst_n(rst_n), .A_20_bus(A_20_bus), .B_14(B_14));
    cluster_type_6 cluster_type_6_i7 (.A_2(A_2), .A_5(A_5), .A_6(A_6), .A_7(A_7), .A1_12_bus(A1_12_bus));
    cluster_type_7 cluster_type_7_i8 (.A_40(A_40), .A_41(A_41), .A_42(A_42), .A_43(A_43), .A_75(A_75), .A_8(A_8), .I(I), .clk(clk), .rst_n(rst_n), .A_28(A_28), .A1_38_bus(A1_38_bus));
    cluster_type_8 cluster_type_8_i9 (.A_75(A_75), .A_8(A_8), .clk(clk), .rst_n(rst_n), .A_94_bus(A_94_bus), .A2_43(A2_43));
    cluster_type_9 cluster_type_9_i10 (.A_8(A_8), .clk(clk), .rst_n(rst_n), .A_40(A_40), .A_41(A_41), .A_42(A_42), .A_43(A_43), .A_75(A_75));
    cluster_type_10 cluster_type_10_i11 (.A_23_bus(A_23_bus), .A_27(A_27), .A_28(A_28), .B_14(B_14), .C(C), .clk(clk), .rst_n(rst_n), .A2_7_bus({success, A_17, A2_7}));
    cluster_type_11 cluster_type_11_i12 (.A_59_bus(A_100_bus), .C(C));
    cluster_type_12 cluster_type_12_i13 (.A_75(A_75), .A2_43(A2_43), .clk(clk), .enable(enable), .rst_n(rst_n), .A_27(A_27), .A_8(A_8));
endmodule
